services:
  app:
    container_name: astro-dev
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules  # Ensure the container’s node_modules isn't overridden
    environment:
      - NODE_ENV=development
    command: npm run dev